spring:
  application:
    name: spring-data-jpa

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 12562903
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialectspring.application.name=spring-data-jpa
